spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/spring_boot_db0?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&requireSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    second:
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&requireSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
#jpa自动生成表
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        formt_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#logging:
#  level:
#    com:
#      itmayiedu: info
server:
  port: 8080
#logging.config=classpath:log4j2-spring.xml
#
#spring.main.allow-bean-definition-overriding=true

## Mysql 1
#mysql.datasource.primary.jdbc-url = jdbc:mysql://localhost:3306/spring_boot_db0?useUnicode=true&characterEncoding=utf-8
#mysql.datasource.primary.username = root
#mysql.datasource.primary.password = root
#
#mysql.datasource.primary.minPoolSize = 5
#mysql.datasource.primary.maxPoolSize = 25
#mysql.datasource.primary.maxLifetime = 20000
#mysql.datasource.primary.borrowConnectionTimeout = 30
#mysql.datasource.primary.loginTimeout = 30
#mysql.datasource.primary.maintenanceInterval = 60
#mysql.datasource.primary.maxIdleTime = 60
#mysql.datasource.primary.testQuery = select 1
#
#
## Mysql 2
#mysql.datasource.second.jdbc-url =jdbc:mysql://localhost:3306/spring_boot_db?useUnicode=true&characterEncoding=utf-8
#mysql.datasource.second.username =root
#mysql.datasource.second.password =root
#
#mysql.datasource.second.minPoolSize = 5
#mysql.datasource.test2.maxPoolSize = 25
#mysql.datasource.second.maxLifetime = 20000
#mysql.datasource.second.borrowConnectionTimeout = 30
#mysql.datasource.second.loginTimeout = 30
#mysql.datasource.second.maintenanceInterval = 60
#mysql.datasource.second.maxIdleTime = 60
#mysql.datasource.second.testQuery = select 1